name: Lint

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: yarn

      - name: Validate current commit (last commit) with commitlint
        run: npx commitlint --last --verbose

      - name: Check formatting
        run: yarn format:check

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint
